stages:
  - pages
  - next
  - sync

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository

image: centos:centos8.4.2105

pages:
  stage: pages
  script:
    - mkdir public
    - mv README.md ./public
    - mv .nojekyll ./public
    - mv CNAME ./public
    - mv favicon.ico ./public
    - mv index.html ./public
  artifacts:
    paths:
      - public
  only:
    - pages

next:
  stage: next
  image: maven:3.6.3-openjdk-17
  script:
    - GPG_FILE=`find / -name xuxiaowei_0x30F97859_SECRET`
    - echo $GPG_FILE
    - gpg --import $GPG_FILE
    - sed -i "s#</servers>#<server><id>ossrh</id><username>$ossrh_user</username><password>$ossrh_pass</password></server>&#" settings.xml
    - git --version
    - NAME=`mvn help:evaluate -Dexpression=project.name -q -DforceStdout -s settings.xml`
    - VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout -s settings.xml`
    - PACKAGING=`mvn help:evaluate -Dexpression=project.packaging -q -DforceStdout -s settings.xml`
    - echo 名称：$NAME
    - echo 版本：$VERSION
    - echo 包：$PACKAGING
    - echo 常量网址：https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - echo 当前分支：$CI_COMMIT_BRANCH
    - echo 主分支：$CI_DEFAULT_BRANCH
    - echo 项目路径：$CI_PROJECT_DIR
    - mvn clean -U package source:jar javadoc:jar deploy -Pgpg -DskipTests -s settings.xml && echo 发布完成
  artifacts:
    paths:
      - target/spring-boot-starter-idempotent-*
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "next"
      changes:
        - ".mvn/**/*"
        - "src/**/*"
        - ".gitlab-ci.yml"
        - "mvnw"
        - "mvnw.cmd"
        - "pom.xml"
        - "settings.xml"
        - "!README.md"

include:
  - project: xuxiaowei-com-cn/spring-boot-starter
    file: sync.yml
    ref: next
