#
# Redis 配置
spring:
  redis:
    host: 127.0.0.1
    database: 6
    password:
    jedis:
      # 连接池
      pool:
        # 最小连接池
        min-idle: 2
#
# 配置
xxw:
  # 幂等配置
  idempotent:
    # 默认 调用之前创建Token（在 Redis 中）
    # 第一优先级：{@link Idempotent#beforeCreateToken}
    # 第二优先级：本参数
    default-before-create-token: false
    # 输入流过滤器（用于将输入流修改为可重复获取的输入流）
    # 布尔类型
    # 默认为：false，不可为空
    input-stream-filter: false
    # 测试路径前缀
    # 默认值：/test
    test-prefix: /test
    # Redis 内容前缀
    # 默认值：idempotent
    prefix: idempotent
    # Redis 调用记录名
    # 默认值：record
    record: record
    # Redis 调用结果名
    # 默认值：result
    result: result
#
# 日志配置
logging:
  level:
    cn.com.xuxiaowei.boot.idempotent: debug
