#
# Redis 配置
spring:
  redis:
    host: 127.0.0.1
    database: 6
    password:
#
# 配置
xxw:
  # 幂等配置
  idempotent:
    # 输入流过滤器（用于将输入流修改为可重复获取的输入流）
    # 布尔类型
    # 默认为：false
    input-stream-filter: false
#
# 日志配置
logging:
  level:
    cn.com.xuxiaowei.boot.idempotent: debug
